   name: Setup Pages
    uses: actions/configure-pages@v3

   name: Build with Jekyll
    uses: actions/jekyll-build-pages@v2

   name: Upload artifact
    uses: actions/upload-pages-artifact@v2

   name: Deploy to GitHub Pages
    uses: actions/deploy-pages@v3

